### ISSUE TITLE
Ajout de dates sur la page presse

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/blog-eig2#69]
La page presse https://entrepreneur-interet-general.etalab.gouv.fr/presse.html commence à se faire longue !

Peut-être séparer la page par promotion et rajouter une date en plus du lien ?

**Comment by bzg** [comment]
J'ai essayé d'améliorer un peu avec https://github.com/etalab/blog-eig2/pull/70 ... mais c'est compliqué de rendre tout ça lisible.  Est-ce que c'est mieux ?

**Comment by AntoineAugusti** [comment]
Merci @bzg, ça me parait déjà mieux comme ça 👍
